healthylife/api/urls.py
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include

from api import views as api_views

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [

    path('', api_views.api, name='api_home'),

    # API Blog URLS
    # path(r'^blog/posts/$', api_views.APIPostList.as_view(), name='post-list'),
    path('blog/posts/', api_views.api_list_posts, name='post-list'),
    # path(r'^api/posts/(?P<pk>\d+)/$', blog_views.APIPostDetail.as_view(), name='post-detail'),

    path('blog/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    # path(r'^api/categories/(?P<pk>\d+)/$', blog_views.APICategoryDetail.as_view(), name='category-detail'),

    path('blog/comments/', api_views.APICommentList.as_view(), name='comment-list'),
    # path(r'^api/comments/(?P<pk>\d+)/$', blog_views.APICommentDetail.as_view(), name='comment-detail'),

    path('blog/tags/', api_views.APITagList.as_view(), name='tag-list'),
    # path(r'^api/tags/(?P<pk>\d+)/$', blog_views.APITagDetail.as_view(), name='tag-detail'),

    # path(r'^users/$', blog_views.APIUserList.as_view(), name='user-list'),
    # path(r'^users/(?P<pk>\d+)/$', blog_views.APIUserDetail.as_view(), name='user-detail'),

    # path(r'^users/login$', blog_views.userLoginAPI, name='user-login-api'),
    # path(r'^users/register/$', blog_views.userRegistrationAPI, name='user-register-api'),


    # API Shop URLS
    path('shop/products/', api_views.api_list_products, name='product-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='product-list'),

    path('shop/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='category-detail'),

    path('shop/reviews/', api_views.APIReviewList.as_view(), name='review-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='review-detail'),

    path('shop/tags/', api_views.APIReviewList.as_view(), name='tag-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='tag-detail'),

    # API Blog URLS
    path('awards/', api_views.api_list_awards, name='awards-list'),

    # API General URLS
    path('users/', api_views.APIUserList.as_view(), name='user-list'),
    path('users/register/', api_views.custom_registration_api, name='user-register'),
    path('api-token-auth/', obtain_jwt_token),

]











#

healthylife/awards/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include
from awards import views as awards_views

urlpatterns = [

    # Awards URLS's
    path('', awards_views.awards, name='awards'),
    path('', awards_views.awards, name='search_awards'),

    path('<str:username>/conseguidos/', awards_views.awards_profile, name='awards_profile'),

    path('<str:award_slug>/', awards_views.award_detail, name='award_detail'),

    # Coupon Urls
    path('cupon/', awards_views.coupon, name='coupon'),
]

healthylife/healthylife/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import DetailView, ListView, UpdateView
from rest_framework.urlpatterns import format_suffix_patterns

from healthylifeapp import views as general_views
from healthylife import settings
from shop import views as shop_views
from shop import urls as shop_urls
from events import views as calendar_views
from events import urls as events_urls
from api import urls as api_urls
from blog import urls as blog_urls
from sportapp import urls as sportapp_urls
from nutritionapp import urls as nutritionapp_urls
from healthapp import urls as healthapp_urls
from awards import urls as awards_urls

admin.site.site_header = 'Barbastro Se Mueve'
admin.autodiscover()

urlpatterns = [

    # Pages URLS's
    path('', general_views.home, name='home'),
    path('conocenos/', general_views.know_us, name='know_us'),
    path('conocenos/colaboradores/<str:username>/', general_views.know_us_collaborator, name='collaborator'),
    path('conocenos/empresas/<str:companyname>/', general_views.know_us_company, name='company'),

    path('trabaja_con_nosotros/', general_views.work_with_our, name='work_with_our'),
    path('informacion_legal/', general_views.legal_information, name='legal_information'),
    path('contacto/', general_views.contact, name='contact'),

    # Subscribe URLS
    path('subscripcion/', general_views.subscribe, name='subscribe'),

    # Admin URLS's
    path('administracion/', admin.site.urls),

    # API Urls
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include((api_urls, 'api'), namespace='api')),

    # Blog URLS's
    path('blog/', include((blog_urls, 'blog'), namespace='blog')),

    # Search URLS's
    path('resultado_busqueda/', general_views.search, name='search'),

    # Shop URLS's
    path('tienda/', include((shop_urls, 'shop'), namespace='shop')),

    # Sport URLS's
    path('deporte/', include((sportapp_urls, 'sportapp'), namespace='sportapp')),

    # Health URLS's
    path('salud/', include((healthapp_urls, 'healthapp'), namespace='healthapp')),

    # Nutrition URLS's
    path('nutricion/', include((nutritionapp_urls, 'nutritionapp'), namespace='nutritionapp')),

    # Statistics URLS's
    path('estadisticas/', general_views.statistics, name='statistics'),

    # Awards URLS's
    path('premios/', include((awards_urls, 'awards'), namespace='awardsapp')),

    # Editor de Texto HTML URL's
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Registro URLS's
    # url(r'^mi_cuenta/$', include('django.contrib.auth.urls')),
    path('registro/', general_views.custom_registration, name='custom_register'),
    #url(r'^registro/completado/$', general_views.registration_complete, name='custom_register_complete'),
    #url(r'^registro/cancelado/$', general_views.registration_disallowed, name='registration_disallowed'),

    # Profile URLS's
    path('mi_cuenta/<str:username>/', general_views.profile, name='profile'),
    # url(r'^mi_cuenta/(?P<username>\w+)/pedidos/$', general_views.ships, name='ships'),
    path('mi_cuenta/<str:username>/deporte/', general_views.sport_profile, name='sport_profile'),
    path('mi_cuenta/<str:username>/nutricion/', general_views.nutrition_profile, name='nutrition_profile'),
    path('mi_cuenta/<str:username>/salud/', general_views.health_profile, name='health_profile'),
    #url(r'^mi_cuenta/(?P<username>\w+)/premios/$', general_views.awards_profile, name='awards_profile'),
    path('mi_cuenta/<str:username>/colaborador/', general_views.collaborator_profile, name='collaborator_profile'),

    # Calendar URLS's
    path('calendario/', include((events_urls, 'events'), namespace='calendar')),

    # Company URLS's
    #url(r'^empresas/(?P<company>\w+)/empresa/$', views.company, name='company'),

    # Collaborators URLS's
    #url(r'^colaboradores/(?P<username>\w+)/$', views.company, name='collaborators'),

    # Login URLS's
    path('acceso/', general_views.custom_login, name='custom_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('activacion/<uuid:uidb64>/<uuid:token>/', general_views.custom_activation, name='activation'),
    path('reset/', general_views.custom_reset_password, name='reset'),
    path('reset_form/<uuid:uidb64>/<uuid:token>/', general_views.custom_reset_password_form, name='reset_form'),


    #url(r'^mi_cuenta/password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    #url(r'^mi_cuenta/password_change_done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #url(r'^mi_cuenta/password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #url(r'^mi_cuenta/password_reset_done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #url(r'^mi_cuenta/password_confirm/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #url(r'^mi_cuenta/password_reset_complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

# Format suffixes
#urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthylife/shop/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.conf.urls import url
from django.urls import path, include, re_path
from django.conf.urls.static import static
from shop import views as shop_views
from django.conf import settings

urlpatterns = [

    # Products Shop Urls
    path('productos/', shop_views.product_list, name='product_list'),
    path('productos/<str:product_slug>/', shop_views.product_detail, name='product_detail'),
    path('productos/<str:product_slug>)/comentario', shop_views.add_review, name='add_review'),

    # Category Urls
    path('categorias/<str:shop_category_slug>/', shop_views.product_list, name='product_list_category'),

    #Search Urls
    path('productos/', shop_views.product_list, name='shop_search'),

    # Payments Urls
    path('pago/realizado', shop_views.payment_done, name='payment_done'),
    path('pago/cancelado', shop_views.payment_canceled, name='payment_canceled'),

    # Shipping Urls
    path('direccion_envio/', shop_views.address_checkout, name='address_checkout'),
    path('metodo_envio/', shop_views.shipping_checkout, name='shipping_checkout'),
    path('metodo_pago/', shop_views.payment_checkout, name='payment_checkout'),

    path('pedido/', shop_views.order_checkout, name='order_checkout'),

    # ShopingChart Urls
    path('carrito/', shop_views.shoppingcart, name='shoppingcart_detail'),
    path('carrito/nuevo/<int:product_id>/', shop_views.cartAdd, name='shoppingcart_add'),

    #Profile Urls
    path('mi_cuenta/<str:username>/pedidos/', shop_views.ships, name='ships'),

]

healthylife/shop/forms.py
#!/usr/local/bin/python
# coding: utf-8

from django import forms
from shop import models as shop_models
#from shop.templatetags import calculateStockItem

# General Forms
class SearchForm(forms.Form):
    """Formulario de busqueda"""
    word = forms.CharField(label='', widget=forms.TextInput(attrs={'id': 'search_word', 'placeholder':'Busca lo que quieras', "size": 50, 'class': 'form-control'}))


class PaymentCheckout(forms.Form):
    credir_card_number = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Número de tarjeta'}))
    credir_card_date = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Número de tarjeta'}))
    credir_card_code = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Número de tarjeta'}))


class ProductFilter(forms.ModelForm):
    #category = forms.ChoiceField(label='Categoria', required=False)
    #category = forms.ModelForm()
    name = forms.CharField(label='Nombre', required=False, widget=forms.TextInput(attrs={'placeholder':'Busca un producto'}))
    minimum_price = forms.DecimalField(label='Precio minimo', required=False, max_digits=8, decimal_places=2, widget=forms.NumberInput(attrs={'placeholder': 'Mínimo'}))
    maximum_price = forms.DecimalField(label='Precio maximo', required=False, max_digits=8, decimal_places=2, widget=forms.NumberInput(attrs={'placeholder': 'Máximo'}))
    # https://www.w3schools.com/howto/howto_js_rangeslider.asp
    ORDER_BY = ((1, ("Precio de menor a mayor")), (2, ("Precio de mayor a menor")))
    order_by = forms.ChoiceField(choices = ORDER_BY, label="Ordenar", initial=1, widget=forms.Select(), required=False)
    #without_stock = forms.BooleanField(label='Sin stock', required=False, initial=False)
    with_discount = forms.BooleanField(label='Con descuento', required=False)

    def __init__(self, *args, **kwargs):
        super(ProductFilter, self).__init__(*args, **kwargs)
        self.fields['category'] = forms.ModelChoiceField(
            label='Categoria',
            required=False,
            queryset=shop_models.Category.objects.all())

    class Meta:
        model = shop_models.Product
        #include = ['category', 'name', 'price']
        exclude = ['description', 'slug', 'price', 'album', 'size', 'weight', 'status', 'discount', 'stock']


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(0, 26)]

class ShoppingCartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, help_text = 'Uds.')


REVIEW_MARK_CHOICES = [(i, str(i)) for i in range(0, 11)]
# Comment Forms
class ReviewFormAuthenticated(forms.ModelForm):
    title = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'id': 'comment_title', 'placeholder':'Título del comentario'}))
    content = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'id': 'comment_content', 'placeholder':'Contenido del comentario'}))
    mark = forms.TypedChoiceField(required=True, choices=REVIEW_MARK_CHOICES, coerce=int, help_text = '', label='Puntuación')

    class Meta:
        model = shop_models.Review
        fields = ['title', 'content', 'mark']


class ReviewFormNotAuthenticated(forms.ModelForm):
    name = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'id': 'comment_title', 'placeholder':'Nombre'}))
    email = forms.EmailField(required=True, label='', widget=forms.EmailInput(attrs={'id': 'comment_email', 'placeholder': 'Eamil'}))
    title = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'id': 'comment_title', 'placeholder':'Título del comentario'}))
    content = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'id': 'comment_content', 'placeholder':'Contenido del comentario'}))
    mark = forms.TypedChoiceField(required=True, choices=REVIEW_MARK_CHOICES, coerce=int, help_text = '', label='Puntuación')

    class Meta:
        model = shop_models.Review
        fields = ['name', 'mark', 'title', 'content', 'email']
#

healthylife/templates/shop/address_checkout.html
{% extends 'base.html' %}
{% load static %}
{% load shop_tags %}

{% block address_checkout %}

<!-- Start Oreder Checkout Bradcaump area -->
<div class="ht__bradcaump__area" style="background: rgba(0, 0, 0, 0) url(images/bg/2.jpg) no-repeat scroll center center / cover ;">
  <div class="ht__bradcaump__wrap">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="bradcaump__inner text-center">
            <h2 class="bradcaump-title">Checkout</h2>
            <nav class="bradcaump-inner">
              <a class="breadcrumb-item" href="index.html">Home</a>
              <span class="brd-separetor">/</span>
              <span class="breadcrumb-item active">Checkout</span>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Start Address Checkout Area -->
  <section class="our-checkout-area ptb--120 bg__white">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="ckeckout-left-sidebar">

            <!-- Start Address Checkout Form-->
            <div class="checkout-form">
              <h2 class="section-title-3">Dirección de Envío</h2>

              <div class="checkout-form-inner">
                <div class="single-checkout-box">
                  <input type="text" placeholder="First Name*">
                  <input type="text" placeholder="Last Name*">
                </div>
                <div class="single-checkout-box">
                  <input type="email" placeholder="Emil*">
                  <input type="text" placeholder="Phone*">
                </div>
                <div class="single-checkout-box">
                  <textarea name="message" placeholder="Message*"></textarea>
                </div>
                <div class="single-checkout-box select-option mt--40">
                  <select>
                    <option>Country*</option>
                    <option>Bangladesh</option>
                    <option>Bangladesh</option>
                    <option>Bangladesh</option>
                    <option>Bangladesh</option>
                  </select>
                  <input type="text" placeholder="Company Name*">
                </div>
                <div class="single-checkout-box">
                  <input type="email" placeholder="State*">
                  <input type="text" placeholder="Zip Code*">
                </div>
                <div class="single-checkout-box checkbox">
                  <input id="remind-me" type="checkbox">
                  <label for="remind-me"><span></span>Create a Account ?</label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    <!-- Start Address Checkout Menu -->
    <div class="row">
      <div class="col-md-8 col-sm-7 col-xs-12">
        <div class="buttons-cart">
          <a href="{% url 'shop:shoppingcart_detail' %}">Volver al Carrito</a>
          <a href="{% url 'shop:shipping_checkout' %}">Método de Envío</a>
        </div>
      </div>
    </div>

  </div>
</section>

{% endblock %}

healthylife/templates/shop/answer_form.html
{% load static %}

<form id="review-form" method="POST" action="{% url 'shop:add_review' product_slug=product.slug %}">
  {% csrf_token %}
  <!--<div class="single-review-form">-->
  <div class="single-contact-form">
    <div class="contact-box subject">
      {{ review_form.mark }}
    </div>
  </div>
  <div class="single-contact-form">
    <div class="contact-box subject">
      {{ review_form.name }}
    </div>
  </div>
  <div class="single-contact-form">
    <div class="contact-box subject">
      {{ review_form.email }}
    </div>
  </div>
  <div class="single-contact-form">
    <div class="contact-box subject">
      {{ review_form.title }}
    </div>
  </div>
  <div class="single-contact-form">
    <div class="contact-box subject">
      {{ review_form.content }}
    </div>
  </div>
  <div class="contact__btn">
    <input type="submit" class="fv-btn" value="Opinar">
    <input type="hidden" name="review_parent_id" value="{{ review.id }}">
  </div>
</form>

healthylife/templates/shop/last_products.html
{% load static %}

  <!-- Start Our Product Area -->
  
  <section class="htc__best__product__area pb--100 bg__white">
    <div class="container">

      <!-- Start Last Products Title Area -->
      <div class="row">
        <div class="col-xs-12">
          <div class="section__title text-center">
            <h2 class="title__line">Últimos Productos</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="best__product__list clearfix mt--30">

          <!-- Start Single Product -->
          {% for product in last_products %}
          <div class="col-md-3 col-lg-3 col-sm-4 col-xs-12">
            <div class="best__product foo">
              <div class="best__product__inner">
                <div class="best__product__thumb">
                  {% for item in product.album.image_set.all %}
                  {% if item.header_image %}
                  <a href="">
                    <img src="{{ item.image.url }}" alt="blog images">
                  </a>
                  {% endif %}
                  {% endfor %}
                </div>
                <div class="bst__pro__hover__info">
                  <div class="bst__pro__hover__action">
                    <h2><a href="{% url 'shop:product_detail' product.slug %}">{{ product.name }}</a></h2>
                    <span class="bst__pro__prize">{{ product.price }} €</span>
                    <ul class="bst__pro__action">
                      <!--<li><a data-toggle="modal" data-target="#productModal" title="Quick View" class="quick-view modal-view detail-link" href="#"><span class="ti-plus"></span></a></li>-->
                      <li><a title="Add To Cart" href="{% url 'shop:shoppingcart_add' product_id=product.id %}"><span class="ti-shopping-cart"></span></a></li>
                      <!--<li><a title="Add To Wishlist" class="add-to-cart" href="wishlist.html"><span class="ti-heart"></span></a></li>-->
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      <!-- Go To Shop Button -->
      <div class="row mt--60">
        <div class="col-md-12">
          <div class="htc__loadmore__btn">
            <a href="{% url 'shop:product_list' %}">Ir a la Tienda</a>
          </div>
        </div>
      </div>
    </div>
</section>

healthylife/templates/shop/review_form.html
{% load static %}

  <form id="review-form" method="POST" action="{% url 'shop:add_review' product_slug=product.slug %}">
    {% csrf_token %}
    <!--<div class="single-review-form">-->
    <div class="single-contact-form">
      <div class="contact-box subject">
        {{ review_form.mark }}
      </div>
    </div>
    <div class="single-contact-form">
      <div class="contact-box subject">
        {{ review_form.name }}
      </div>
    </div>
    <div class="single-contact-form">
      <div class="contact-box subject">
        {{ review_form.email }}
      </div>
    </div>
    <div class="single-contact-form">
      <div class="contact-box subject">
        {{ review_form.title }}
      </div>
    </div>
    <div class="single-contact-form">
      <div class="contact-box subject">
        {{ review_form.content }}
      </div>
    </div>
    <div class="contact__btn">
      <input type="submit" class="fv-btn" value="Opinar">
      <!--<a class="blog__comment__reply__close">CANCELAR</a>-->
    </div>
  </form>

healthylife/templates/shop/shoppingcart.html
{% extends 'base.html' %}
{% load static %}
{% load shop_tags %}

{% block shoppincart %}

<!-- Start ShoppingCart Bradcaump Area -->
  <div class="ht__bradcaump__area" style="background: rgba(0, 0, 0, 0) url({% static 'images/health_banner_1.jpg' %}) no-repeat scroll center center / cover ;">
    <div class="ht__bradcaump__wrap">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="bradcaump__inner text-center">
              <h2 class="bradcaump-title">Cart</h2>
              <nav class="bradcaump-inner">
                <a class="breadcrumb-item" href="index.html">Home</a>
                <span class="brd-separetor">/</span>
                <span class="breadcrumb-item active">Cart</span>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Start ShoppingCart Area -->
  <div class="cart-main-area ptb--120 bg__white">
    <div class="container">
      <div class="row">
        {% if shoppingcart|length > 0 %}
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="table-content table-responsive">
              <table>
                <thead>
                  <tr>
                    <th class="product-thumbnail">Imagen</th>
                    <th class="product-name">Producto</th>
                    <th class="product-price">Price</th>
                    <th class="product-quantity">Cantidad</th>
                    <th class="product-subtotal">Total</th>
                    <th class="product-remove">Actualizar</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in shoppingcart %}
                  <form method='POST' action="{% url 'shop:shoppingcart_add' product_id=item.product.id %}">
                  <tr>
                    <td class="product-thumbnail"><img src="{{ item.product.image.url }}" alt="product img" /></td>
                    <td class="product-name"><a href="{% url 'shop:product_detail' product_slug=product.slug %}">{{ item.product.name }}</a></td>
                    <td class="product-price"><span class="amount">{{ item.product.price }} €</span></td>
                    <td class="product-quantity">{{ item.shoppingcart_form.quantity }}</td>
                    <td class="product-subtotal">£165.00</td>
                    <!-- Actualizar -->
                    <td><input type="submit" value="Actualizar"></td>
                  </tr>
                  </form>
                  {% endfor %}
              </tbody>
            </table>
          </div>

          <div class="row">
            <div class="col-md-8 col-sm-7 col-xs-12">
              <div class="buttons-cart">
                <!--<input type="submit" value="Actualizar Carrito" />-->
                <a href="{% url 'shop:product_list' %}">Volver a la Tienda</a>
              </div>
              <div class="coupon">
                {% if user.is_authenticated %}
                  <h3><a href="{% url 'awardsapp:awards_profile' user.username %}">Ver tus premios y descuentos</a></h3>
                {% endif %}
                <form action="" method="POST">
                  {% csrf_token %}
                  <input type="text" placeholder="Coupon code" />
                  <input type="submit" value="Apply Coupon" />
                </form>
              </div>
            </div>
            <div class="col-md-4 col-sm-5 col-xs-12">
              <div class="cart_totals">
                <h2>Resumen</h2>
                <br>
                <table>
                  <tbody>
                    <tr class="cart-subtotal">
                      <th>Subtotal</th>
                      <td><span class="amount">£215.00</span></td>
                    </tr>
                    <tr class="shipping">
                      <th>Impuestos</th>
                      <td><span class="amount">£215.00</span></td>
                    </tr>
                    <!--<tr class="shipping">
                      <td>
                        <ul id="shipping_method">
                          <li>
                            <input type="radio" />
                            <label>
                              Flat Rate: <span class="amount">£7.00</span>
                            </label>
                          </li>
                          <li>
                            <input type="radio" />
                            <label>
                              Free Shipping
                            </label>
                          </li>
                          <li></li>
                        </ul>
                        <p><a class="shipping-calculator-button" href="#">Calculate Shipping</a></p>
                      </td>
                    </tr>-->
                    <tr class="order-total">
                      <th>Total</th>
                      <td>
                        <strong>
                          <span class="amount">£215.00</span>
                        </strong>
                      </td>
                    </tr>
                  </tbody>
                </table>

                <div class="wc-proceed-to-checkout">
                  <a href="{% url 'shop:address_checkout' %}">Finalizar Pedido</a>
                </div>
              </div>
            </div>
          </div>
      </div>
      {% else %}
      <div class="col-md-8 col-sm-7 col-xs-12">
        <div class="buttons-cart">
          <p>Tu carrito esta vacio.</p>
          <a href="{% url 'shop:product_list' %}">Volver a la Tienda</a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

healthylife/templates/shop/shoppingcart_menu.html
<!-- Start Shopping Cart Icon Menu Area -->
<div class="shopping__cart">
  <div class="shopping__cart__inner">

    <div class="offsetmenu__close__btn">
      <a href="#"><i class="zmdi zmdi-close"></i></a>
    </div>

    {% if shoppingcart|length > 0 %}
      <div class="shp__cart__wrap">
        {% for item in shoppingcart %}
          <div class="shp__single__product">
            <div class="shp__pro__thumb">
              <a href="#">
                <img src="{{ item.product.image.url }}" alt="product images">
              </a>
            </div>
            <div class="shp__pro__details">
              <form method='POST' action="{% url 'shop:shoppingcart_add' product_id=item.product.id %}">
                {% csrf_token %}
                <h2><a href="{% url 'shop:product_detail' product_slug=product.slug %}">{{ item.product.name }}</a></h2>
                {{ item.product.price }} €
                {{ item.shoppingcart_form.quantity }}
                <input type="submit" value="Aactualizar">
              </div>
              <!--<div class="remove__btn">
                <a href="#" title="Remove this item">Actualizar</a>
              </div>-->
            </div>
        {% endfor %}
      </div>

      <ul class="shoping__total">
        <li class="subtotal">Subtotal:</li>
        <li class="total__price">$130.00</li>
      </ul>

      <ul class="shopping__btn">
        <li><a href="{% url 'shop:shoppingcart_detail' %}">Ver Carrito</a></li>
        <!--<li class="shp__checkout"><a href="checkout.html">Checkout</a></li>-->
      </ul>

    {% else %}

      <p>Tu carrito esta vacio.</p>
      <ul class="shopping__btn">
        <li>
          <a href="{% url 'shop:product_list' %}">Visita la Tienda</a>
        </li>
      </ul>
    {% endif %}
  </div>
</div>