healthylife/api/urls.py
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include

from api import views as api_views

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [

    path('', api_views.api, name='api_home'),

    # API Blog URLS
    # path(r'^blog/posts/$', api_views.APIPostList.as_view(), name='post-list'),
    path('blog/posts/', api_views.api_list_posts, name='post-list'),
    # path(r'^api/posts/(?P<pk>\d+)/$', blog_views.APIPostDetail.as_view(), name='post-detail'),

    path('blog/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    # path(r'^api/categories/(?P<pk>\d+)/$', blog_views.APICategoryDetail.as_view(), name='category-detail'),

    path('blog/comments/', api_views.APICommentList.as_view(), name='comment-list'),
    # path(r'^api/comments/(?P<pk>\d+)/$', blog_views.APICommentDetail.as_view(), name='comment-detail'),

    path('blog/tags/', api_views.APITagList.as_view(), name='tag-list'),
    # path(r'^api/tags/(?P<pk>\d+)/$', blog_views.APITagDetail.as_view(), name='tag-detail'),

    # path(r'^users/$', blog_views.APIUserList.as_view(), name='user-list'),
    # path(r'^users/(?P<pk>\d+)/$', blog_views.APIUserDetail.as_view(), name='user-detail'),

    # path(r'^users/login$', blog_views.userLoginAPI, name='user-login-api'),
    # path(r'^users/register/$', blog_views.userRegistrationAPI, name='user-register-api'),


    # API Shop URLS
    path('shop/products/', api_views.api_list_products, name='product-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='product-list'),

    path('shop/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='category-detail'),

    path('shop/reviews/', api_views.APIReviewList.as_view(), name='review-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='review-detail'),

    path('shop/tags/', api_views.APIReviewList.as_view(), name='tag-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='tag-detail'),

    # API Blog URLS
    path('awards/', api_views.api_list_awards, name='awards-list'),

    # API General URLS
    path('users/', api_views.APIUserList.as_view(), name='user-list'),
    path('users/register/', api_views.custom_registration_api, name='user-register'),
    path('api-token-auth/', obtain_jwt_token),

]











#

healthylife/blog/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from healthylife import settings
from blog import views as blog_views

urlpatterns = [

    # Blog URLS's
    path('posts/', blog_views.list_posts, name='list_post'),
    path('posts/', blog_views.list_posts, name='blog_search'),

    # hacer generica
    #path(r'^blog/subscripcion/$', blog_views.subscribe, name='subscribe'),

    path('posts/<str:post_slug>/', blog_views.detail_post, name='detail_post'),
    path('posts/<str:post_slug>/comentario', blog_views.add_comment, name='add_comment'),

    path('comentarios/<int:comment_id>/borrar/', blog_views.delete_comment, name='delete_comment'),

    # path(r'^blog/(?P<post_slug>\w+)/(?P<comment_parent_id>\w+)/comentado/$', views.comment, name='comment'),
    path('categorias/<str:category>/', blog_views.category_posts, name='category_posts'),
    path('autores/<str:username>/', blog_views.author_posts, name='author_posts'),
    path('etiquetas/<str:tag_slug>/', blog_views.tag_posts, name='tag_posts'),

]

healthylife/healthylife/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import DetailView, ListView, UpdateView
from rest_framework.urlpatterns import format_suffix_patterns

from healthylifeapp import views as general_views
from healthylife import settings
from shop import views as shop_views
from shop import urls as shop_urls
from events import views as calendar_views
from events import urls as events_urls
from api import urls as api_urls
from blog import urls as blog_urls
from sportapp import urls as sportapp_urls
from nutritionapp import urls as nutritionapp_urls
from healthapp import urls as healthapp_urls
from awards import urls as awards_urls

admin.site.site_header = 'Barbastro Se Mueve'
admin.autodiscover()

urlpatterns = [

    # Pages URLS's
    path('', general_views.home, name='home'),
    path('conocenos/', general_views.know_us, name='know_us'),
    path('conocenos/colaboradores/<str:username>/', general_views.know_us_collaborator, name='collaborator'),
    path('conocenos/empresas/<str:companyname>/', general_views.know_us_company, name='company'),

    path('trabaja_con_nosotros/', general_views.work_with_our, name='work_with_our'),
    path('informacion_legal/', general_views.legal_information, name='legal_information'),
    path('contacto/', general_views.contact, name='contact'),

    # Subscribe URLS
    path('subscripcion/', general_views.subscribe, name='subscribe'),

    # Admin URLS's
    path('administracion/', admin.site.urls),

    # API Urls
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include((api_urls, 'api'), namespace='api')),

    # Blog URLS's
    path('blog/', include((blog_urls, 'blog'), namespace='blog')),

    # Search URLS's
    path('resultado_busqueda/', general_views.search, name='search'),

    # Shop URLS's
    path('tienda/', include((shop_urls, 'shop'), namespace='shop')),

    # Sport URLS's
    path('deporte/', include((sportapp_urls, 'sportapp'), namespace='sportapp')),

    # Health URLS's
    path('salud/', include((healthapp_urls, 'healthapp'), namespace='healthapp')),

    # Nutrition URLS's
    path('nutricion/', include((nutritionapp_urls, 'nutritionapp'), namespace='nutritionapp')),

    # Statistics URLS's
    path('estadisticas/', general_views.statistics, name='statistics'),

    # Awards URLS's
    path('premios/', include((awards_urls, 'awards'), namespace='awardsapp')),

    # Editor de Texto HTML URL's
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Registro URLS's
    # url(r'^mi_cuenta/$', include('django.contrib.auth.urls')),
    path('registro/', general_views.custom_registration, name='custom_register'),
    #url(r'^registro/completado/$', general_views.registration_complete, name='custom_register_complete'),
    #url(r'^registro/cancelado/$', general_views.registration_disallowed, name='registration_disallowed'),

    # Profile URLS's
    path('mi_cuenta/<str:username>/', general_views.profile, name='profile'),
    # url(r'^mi_cuenta/(?P<username>\w+)/pedidos/$', general_views.ships, name='ships'),
    path('mi_cuenta/<str:username>/deporte/', general_views.sport_profile, name='sport_profile'),
    path('mi_cuenta/<str:username>/nutricion/', general_views.nutrition_profile, name='nutrition_profile'),
    path('mi_cuenta/<str:username>/salud/', general_views.health_profile, name='health_profile'),
    #url(r'^mi_cuenta/(?P<username>\w+)/premios/$', general_views.awards_profile, name='awards_profile'),
    path('mi_cuenta/<str:username>/colaborador/', general_views.collaborator_profile, name='collaborator_profile'),

    # Calendar URLS's
    path('calendario/', include((events_urls, 'events'), namespace='calendar')),

    # Company URLS's
    #url(r'^empresas/(?P<company>\w+)/empresa/$', views.company, name='company'),

    # Collaborators URLS's
    #url(r'^colaboradores/(?P<username>\w+)/$', views.company, name='collaborators'),

    # Login URLS's
    path('acceso/', general_views.custom_login, name='custom_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('activacion/<uuid:uidb64>/<uuid:token>/', general_views.custom_activation, name='activation'),
    path('reset/', general_views.custom_reset_password, name='reset'),
    path('reset_form/<uuid:uidb64>/<uuid:token>/', general_views.custom_reset_password_form, name='reset_form'),


    #url(r'^mi_cuenta/password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    #url(r'^mi_cuenta/password_change_done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #url(r'^mi_cuenta/password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #url(r'^mi_cuenta/password_reset_done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #url(r'^mi_cuenta/password_confirm/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #url(r'^mi_cuenta/password_reset_complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

# Format suffixes
#urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthylife/blog/models.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from healthylife.decorators import autoconnect
from healthylifeapp import models as general_models

import datetime

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Blog models
class Tag(models.Model):
    name = models.CharField(primary_key=True, max_length=50, unique=True)
    slug = models.CharField(max_length=100, blank=True)
    author = models.ForeignKey(User, editable=False, null=True, blank=True, related_name='blog_tag_author', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField()

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        """
        metodo de la clase Tag para calcular el slug de una etiqueta y actualizar la fecha de creación
        """
        self.slug = self.name.replace(" ", "_").lower()
        self.updated_date = datetime.datetime.now()
        super(Tag, self).save(*args, **kwargs)


@autoconnect
class Category(models.Model):
    """Modelo para las categorias del blog"""
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, blank=True)
    description = models.CharField(max_length=200)
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField()
    parent = models.ForeignKey('self', related_name='children', null=True, blank=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, editable=False, null=True, blank=True, related_name='post_category_author', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __unicode__(self):
        return self.name

    def pre_save(self, *args, **kwargs):
        """
        """
        self.slug = self.name.replace(" ", "_").lower()
        self.updated_date = datetime.datetime.now()


class PostType(models.Model):
    pass
    # nombre
    # plantilla


@autoconnect
class Post(models.Model):
    """Modelo para los articulos del blog"""
    Status = ((1, "Publicado"), (2, "Borrador"), (3, "Eliminado"))
    status = models.IntegerField(choices=Status, default=2, blank=True)
    title = models.CharField(max_length=100, blank=False)
    slug = models.CharField(max_length=100, default='', blank=True)
    description = models.CharField(max_length=200, blank=False)
    content = RichTextUploadingField('content', config_name='full')
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    created_date = models.DateTimeField()
    updated_date = models.DateTimeField()
    author = models.ForeignKey(User, editable=False, null=True, blank=True, related_name='post_author', on_delete=models.SET_NULL)
    album = models.ForeignKey(general_models.Album, default=1, blank=True, null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, related_name='post_tags')


    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        metodo de la clase post para calcular el slug de un post y crear un album asociado a ese post
        """
        self.slug = self.title.replace(" ", "_").lower()
        self.updated_date = datetime.datetime.now()
        if not self.pk:
            self.created_date = datetime.datetime.now()
            album = general_models.Album.objects.create(name='album ' + self.title, author=self.author)
            self.album = album
            general_models.Image.objects.create(album=self.album, header_image=True, image='photos/header_post_default_image.jpg')
        general_models.Album.objects.filter(id=self.album.id).update(name='Album Post ' + self.title)
        super(Post, self).save(*args, **kwargs)

    def publishPost(self):
        """metodo de la clase post para publicar en redes sociles un post"""
        pass


@autoconnect
class Comment(models.Model):
    """
    https://stackoverflow.com/questions/44837733/how-to-make-add-replies-to-comments-in-django
    """
    Status = ((1, "Publicado"), (2, "Pendiente de Revision"), (3, "Eliminado"))
    status = models.IntegerField(choices=Status, default=2)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField()
    author = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', related_name='answers', null=True, blank=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.updated_date = datetime.datetime.now()
        super(Comment, self).save(*args, **kwargs)

    def post_save(self, **kwargs):
        pass
        # self.notifyNewComment()

    def notifyNewComment(self):
        self.status = 1
        print("notificacion enviada")



#

healthylife/blog/forms.py
#!/usr/local/bin/python
# coding: utf-8

from django import forms

#from ckeditor_uploader.widgets import CKEditorWidget, CKEditorUploadingWidget

from blog import models as blog_models

# Blog forms
class PostForm(forms.ModelForm):

    class Meta:
        model = blog_models.Post
        fields = []


class PostFilter(forms.ModelForm):
    title = forms.CharField(label='Título', required=False, widget=forms.TextInput(attrs={'placeholder': 'Busca'}))
    #minimum_date = forms.DateField(label='fecha mínima', required=False, widget=forms.DateInput(attrs={ 'placeholder': u'Fecha mínima'}))
    #maximum_date = forms.DateField(label='fecha máxima', required=False, widget=forms.DateInput(attrs={'placeholder': u'Fecha máxima'}))
    ORDER_BY = ((1, ("Más antiguos primero")), (2, ("Más recientes primero")))
    order_by = forms.ChoiceField(choices = ORDER_BY, label="Ordenar", initial=1, widget=forms.Select(), required=False)

    def __init__(self, *args, **kwargs):
        super(PostFilter, self).__init__(*args, **kwargs)
        self.fields['category'] = forms.ModelChoiceField(
            label='Categoría',
            required=False,
            queryset=blog_models.Category.objects.all())
        """
        self.fields['tags'] = forms.ModelChoiceField(
            widget=forms.CheckboxSelectMultiple,
            label='Etiquetas',
            required=False,
            queryset=blog_models.Tag.objects.all())
        """

    class Meta:
        model = blog_models.Post
        exclude = ['description', 'content', 'updated_date', 'tags', 'created_date']


class CommentForm(forms.ModelForm):

    class Meta:
        model = blog_models.Comment
        fields = '__all__'


class CommentFormAuthenticated(forms.Form):
    title = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'id': 'comment_title', 'placeholder': u'Título del comentario'}))
    content = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'id': 'comment_content', 'placeholder': 'Contenido del comentario'}))

    """
    class Meta:
        model = blog_models.Comment
        fields = ['title', 'content']
    """

class CommentFormNotAuthenticated(forms.Form):
    name = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'id': 'comment_title', 'placeholder':'Nombre'}))
    email = forms.EmailField(label='', required=True, widget=forms.EmailInput(attrs={'id': 'comment_email', 'placeholder': u'Correo electrónico'}))
    title = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'id': 'comment_title', 'placeholder': u'Título del comentario'}))
    content = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'id': 'comment_content', 'placeholder': 'Contenido del comentario'}))

    """
    class Meta:
        model = blog_models.Comment
        fields = ['name', 'title', 'content', 'email']
    """





    #

healthylife/templates/blog/last_posts.html
{% load static %}

<!-- Start Last Posts Home Area -->
<section class="htc__blog__area bg__white pb--100">
  <div class="container">

    <!-- Start Title Area -->
    <div class="row">
      <div class="col-xs-12">
        <div class="section__title text-center">
          <h2 class="title__line">Últimas Noticias</h2>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="blog__wrap clearfix mt--60 xmt-30">

        <!-- Start Single Blog -->
        {% for post in last_posts %}
          <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
            <div class="blog foo">
              <div class="blog__inner">
                <div class="blog__thumb">

                  <!-- Star Header Image Area -->
                  {% for item in post.album.image_set.all %}
                    {% if item.header_image %}
                      <a href="{% url 'blog:detail_post' post_slug=post.slug %}">
                        <img src="{{ item.image.url }}" alt="blog images">
                      </a>
                    {% endif %}
                  {% endfor %}
                </div>
                <br>
                <h3>{{ post.title }}</h3>
                <br>
                <!--<p>Date: {{ post.created_date.day }}/{{ post.created_date.month }}/{{ post.created_date.year }}</p>-->
                <p>Category:<a href="{% url 'blog:category_posts' category=post.category.slug %}"> {{ post.category.name }}</a></p>
                <p>Author:<a href="{% url 'blog:author_posts' username=post.author.username %}"> {{ post.author.username }}</a></p>
                <br>
                <p>{{ post.description }}</p>
                <br>
                <div class="blog__btn">
                  <a class="read__more__btn" href="{% url 'blog:detail_post' post_slug=post.slug %}">Leer Más</a>
                </div>
              </div>
            </div>
          </div>

        {% endfor %}

      </div>
    </div>
    <!-- Go To Blog Button -->
        <div class="row mt--60">
            <div class="col-md-12">
                <div class="htc__loadmore__btn">
                    <a href="{% url 'blog:list_post' %}">Ir al Blog</a>
                </div>
            </div>
        </div>
  </div>
</section>

healthylife/templates/blog/post_detail.html
{% extends "blog.html" %}
{% load static %}
{% load blog_tags %}

{% block post_detail %}

  <!-- Start Post Detail Area -->
  <section class="blog-details-wrap ptb--120 bg__white">
    <div class="container">

      {% include 'blog_filter.html' %}

      <div class="row">
        <div class="blog__wrap blog--page clearfix">
            <div class="blog-details-top">

              <!-- Start Post Deatil Header Image -->
              <div class="blog-details-thumb-wrap">
                <div class="blog-details-thumb">
                  {% for item in images %}
                    {% if item.header_image %}
                      <img src="{{ item.image.url }}" alt="blog images">
                    {% endif %}
                  {% endfor %}
                </div>
                <!--<div class="upcoming-date">
                  14<span class="upc-mth">Sep,2017</span>
                  {{ post.created_date }}
                </div>-->
              </div>

              <!-- Start Post Deatil Area -->
              <h2>{{ post.title }}</h2>
              <div class="blog-admin-and-comment">
                <p><a href="{% url 'blog:author_posts' username=post.author.username %}">{{ post.author.username }}</a></p>
                <p class="separator">|</p>
                <p><a href="{% url 'blog:category_posts' category=post.category.slug %}">{{ post.category.name }}</a></p>
                <p class="separator">|</p>
                <p>{{ post.created_date }}</p>
              </div>
              <h3>{{ post.description }}</h3><br>
              <div class="blog-details-pra">
                {{ post.content | safe }}
              </div>

              <div class="postandshare">
                <div class="blog-social-icon">
                  <h2 class="ft__title">Compartir</h2>
                  <!--<ul class="social__icon">
                    <li><a href="https://twitter.com/BarbastroSMueve" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
                    <li><a href="https://www.instagram.com/barbastrosemueve/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
                    <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
                    <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-google"></i></a></li>
                    <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-email"></i></a></li>
                    <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
                  </ul>-->
                  <div class="sharethis-inline-share-buttons"></div>
                </div>
              </div>

              <div class="postandshare">
                <div class="our-blog-tag">
                  <h2 class="ft__title">Etiquetas</h2>
                  <ul id="comments" class="tag-menu mt-40">
                    {% for tag in post.tags.all %}
                      <li><a href="{% url 'blog:tag_posts' tag_slug=tag.slug %}">{{tag.name}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>

              <!-- Start Post Deatil Comments Area -->
              <div class="our-blog-comment mt--20">
                <div class="blog-comment-inner">
                  {% if comments %}
                    <h2 class="section-title-2">COMENTARIOS ({{ num_comments }})</h2>

                  <!-- Start Post Deatil Single Comment -->
                  {% for comment in comments %}

                  <div class="single-blog-comment">
                    <div class="blog-comment-thumb">
                      {% get_user_image username=comment.author as user_profile %}
                        {% if user_profile %}
                          <img src="{{ user_profile.profile_image.url }}" alt="comment images">
                        {% else %}
                          <img src="{% static 'images/user_default_image.jpg' %}" alt="comment images">
                        {% endif %}
                    </div>
                    <div class="blog-comment-details">
                      <div class="review__info">
                          <h4><a>{{ comment.title }}</a></h4>
                      </div>
                      <div class="review__date">
                          <span>{{ comment.author }}  |  {{ comment.created_date.day }}/{{ comment.created_date.month }}/{{ comment.created_date.year }}</span>
                      </div>
                      <p>{{ comment.content }}</p>
                      <div class="review__date">
                          <span>
                            <div class="contact-btn">
                              <br>
                              {% get_user_authenticated request username=comment.author as user_authenticated %}
                              {% if user_authenticated %}
                                <a class="fv-btn" href="{% url 'blog:delete_comment' comment_id=comment.id %}">BORRAR</a>
                              {% else %}
                                <a href="#answer_form" class="blog__answer__reply">
                                  <input class="fv-btn blog__answer__reply" type="button" onclick="set_comment_parent_id({{ comment.id|escapejs }})" value="RESPONDER">
                                </a>
                              {% endif %}
                            </div>
                          </span>
                      </div>
                    </div>
                  </div>

                    <!-- Start Post Deatil Replay Comment -->
                    {% for answer in comment.answers.all %}
                      <div class="single-blog-comment comment-reply">
                        <div class="blog-comment-thumb">
                          {% get_user_image username=answer.author as user_profile %}
                            {% if user_profile %}
                              <img src="{{ user_profile.profile_image.url }}" alt="comment images">
                            {% else %}
                              <img src="{% static 'images/user_default_image.jpg' %}" alt="comment images">
                            {% endif %}
                        </div>
                        <div class="blog-comment-details">
                          <div class="review__info">
                              <h4><a>{{ answer.title }}</a></h4>
                          </div>
                          <div class="review__date">
                              <span>{{ answer.author }}  |  {{ comment.created_date.day }}/{{ comment.created_date.month }}/{{ comment.created_date.year }}</span>
                          </div>
                          <p>{{ answer.content }}</p>
                          <div class="review__date">
                              <span>
                                <div class="contact-btn">
                                  <br>
                                  {% get_user_authenticated request username=answer.author as user_authenticated %}
                                  {% if user_authenticated %}
                                    <a class="fv-btn" href="{% url 'blog:delete_comment' comment_id=answer.id %}">BORRAR</a>
                                  {% else %}
                                    <a href="#answer_form" class="blog__answer__reply">
                                      <input class="fv-btn blog__answer__reply" type="button" onclick="set_comment_parent_id({{ comment.id|escapejs }})" value="RESPONDER">
                                    </a>
                                {% endif %}
                                </div>
                              </span>
                          </div>
                        </div>
                      </div>

                    {% endfor %}
                  {% endfor %}
                {% else %}
                      <h2 class="section-title-2">SIN COMENTARIOS</h2>
                {% endif %}
                    </div>
                </div>


              <!-- Start Post Deatil Comment Form Area -->
              <div id="answer_form"  class="our-reply-form-area mt--20">
                <h2 class="contact__title">DEJA TU COMENTARIO</h2>

                <!-- Start Comment Form Area -->
                <div class="blog__comment__form">
                  {% include 'comment_form.html' %}
                </div>
                <!-- Start Anser Form Area -->
                <div class="blog__answer__form hidden">
                  {% include 'answer_form.html' %}
                </div>
              </div>

              <div class="postandshare">
                <div>
                  <h2 class="ft__title">Posts Relacionados</h2>
                  {% include 'related_posts.html' %}
                </div>
              </div>

            </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

healthylife/templates/blog/post_list.html
{% extends "blog.html" %}
{% load static %}
{% load blog_tags %}

{% block post_list %}

  <!-- Start Post List Area -->
  <div class="row">
    <div class="blog__wrap clearfix">

      <!-- Star Simple Post Area -->
      {% if posts|length > 0 %}

        {% for post in posts %}
          <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
            <div class="blog foo">
              <div class="blog__inner">
                <div class="blog__thumb">

                  <!-- Star Header Image Area -->
                  {% for item in post.album.image_set.all %}
                    {% if item.header_image %}
                      <a href="{% url 'blog:detail_post' post_slug=post.slug %}">
                        <img src="{{ item.image.url }}" alt="blog images">
                      </a>
                    {% endif %}
                  {% endfor %}
                </div>

                <br>
                <h3>{{ post.title }}</h3>
                <br>
                <p>Date: {{ post.created_date.day }}/{{ post.created_date.month }}/{{ post.created_date.year }}</p>
                <p>Category:<a href="{% url 'blog:category_posts' category=post.category.slug %}"> {{ post.category.name }}</a></p>
                <p>Author:<a href="{% url 'blog:author_posts' username=post.author.username %}"> {{ post.author.username }}</a></p>
                <br>
                <p>{{ post.description }}</p>
                <br>

                <div class="blog__btn">
                  <a class="read__more__btn" href="{% url 'blog:detail_post' post_slug=post.slug %}">Leer Más</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>

    <!-- Pagination Blog Area -->

    <div class="row mt--60">
      <div class="col-md-12">
        <div class="htc__loadmore__btn">
          {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">Anterior</a>
          {% endif %}
          <a href="">{{ posts.number }}</a>
          {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">Siguiente</a>
          {% endif %}
        </div>
      </div>
    </div>

  {% else %}
    <div class="row mt--60">
      <div class="col-md-12">
        <div class="htc__loadmore__btn">
          <p>No hay publicaciones con tu busqueda.</p>
          <br>
          <a href="{% url 'blog:list_post' %}">Ir al Blog</a>
        </div>
      </div>
    </div>
  {% endif %}
  
{% endblock %}