healthylife/api/urls.py
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include

from api import views as api_views

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [

    path('', api_views.api, name='api_home'),

    # API Blog URLS
    # path(r'^blog/posts/$', api_views.APIPostList.as_view(), name='post-list'),
    path('blog/posts/', api_views.api_list_posts, name='post-list'),
    # path(r'^api/posts/(?P<pk>\d+)/$', blog_views.APIPostDetail.as_view(), name='post-detail'),

    path('blog/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    # path(r'^api/categories/(?P<pk>\d+)/$', blog_views.APICategoryDetail.as_view(), name='category-detail'),

    path('blog/comments/', api_views.APICommentList.as_view(), name='comment-list'),
    # path(r'^api/comments/(?P<pk>\d+)/$', blog_views.APICommentDetail.as_view(), name='comment-detail'),

    path('blog/tags/', api_views.APITagList.as_view(), name='tag-list'),
    # path(r'^api/tags/(?P<pk>\d+)/$', blog_views.APITagDetail.as_view(), name='tag-detail'),

    # path(r'^users/$', blog_views.APIUserList.as_view(), name='user-list'),
    # path(r'^users/(?P<pk>\d+)/$', blog_views.APIUserDetail.as_view(), name='user-detail'),

    # path(r'^users/login$', blog_views.userLoginAPI, name='user-login-api'),
    # path(r'^users/register/$', blog_views.userRegistrationAPI, name='user-register-api'),


    # API Shop URLS
    path('shop/products/', api_views.api_list_products, name='product-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='product-list'),

    path('shop/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='category-detail'),

    path('shop/reviews/', api_views.APIReviewList.as_view(), name='review-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='review-detail'),

    path('shop/tags/', api_views.APIReviewList.as_view(), name='tag-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='tag-detail'),

    # API Blog URLS
    path('awards/', api_views.api_list_awards, name='awards-list'),

    # API General URLS
    path('users/', api_views.APIUserList.as_view(), name='user-list'),
    path('users/register/', api_views.custom_registration_api, name='user-register'),
    path('api-token-auth/', obtain_jwt_token),

]











#

healthylife/blog/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from healthylife import settings
from blog import views as blog_views

urlpatterns = [

    # Blog URLS's
    path('posts/', blog_views.list_posts, name='list_post'),
    path('posts/', blog_views.list_posts, name='blog_search'),

    # hacer generica
    #path(r'^blog/subscripcion/$', blog_views.subscribe, name='subscribe'),

    path('posts/<str:post_slug>/', blog_views.detail_post, name='detail_post'),
    path('posts/<str:post_slug>/comentario', blog_views.add_comment, name='add_comment'),

    path('comentarios/<int:comment_id>/borrar/', blog_views.delete_comment, name='delete_comment'),

    # path(r'^blog/(?P<post_slug>\w+)/(?P<comment_parent_id>\w+)/comentado/$', views.comment, name='comment'),
    path('categorias/<str:category>/', blog_views.category_posts, name='category_posts'),
    path('autores/<str:username>/', blog_views.author_posts, name='author_posts'),
    path('etiquetas/<str:tag_slug>/', blog_views.tag_posts, name='tag_posts'),

]

healthylife/events/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include, re_path
from events import views as calendar_views
from events import models as calendar_models

urlpatterns = [

    # Calendar URLS's
    path('<str:username>/<int:year>/<int:month>/', calendar_views.month, name='month_calendar'),
    path('<str:username>/<int:year>/<int:month>/<int:day>/', calendar_views.day, name='day_calendar'),

    # Event Urls
    path('eventos/', calendar_views.list_events, name='list_events'),
    path('eventos/nuevo/', calendar_views.add_event, name='add_event'),
    path('eventos/<str:slug>/', calendar_views.EventUpdateView.as_view(), name='detail_event'),
]

healthylife/healthylife/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import DetailView, ListView, UpdateView
from rest_framework.urlpatterns import format_suffix_patterns

from healthylifeapp import views as general_views
from healthylife import settings
from shop import views as shop_views
from shop import urls as shop_urls
from events import views as calendar_views
from events import urls as events_urls
from api import urls as api_urls
from blog import urls as blog_urls
from sportapp import urls as sportapp_urls
from nutritionapp import urls as nutritionapp_urls
from healthapp import urls as healthapp_urls
from awards import urls as awards_urls

admin.site.site_header = 'Barbastro Se Mueve'
admin.autodiscover()

urlpatterns = [

    # Pages URLS's
    path('', general_views.home, name='home'),
    path('conocenos/', general_views.know_us, name='know_us'),
    path('conocenos/colaboradores/<str:username>/', general_views.know_us_collaborator, name='collaborator'),
    path('conocenos/empresas/<str:companyname>/', general_views.know_us_company, name='company'),

    path('trabaja_con_nosotros/', general_views.work_with_our, name='work_with_our'),
    path('informacion_legal/', general_views.legal_information, name='legal_information'),
    path('contacto/', general_views.contact, name='contact'),

    # Subscribe URLS
    path('subscripcion/', general_views.subscribe, name='subscribe'),

    # Admin URLS's
    path('administracion/', admin.site.urls),

    # API Urls
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include((api_urls, 'api'), namespace='api')),

    # Blog URLS's
    path('blog/', include((blog_urls, 'blog'), namespace='blog')),

    # Search URLS's
    path('resultado_busqueda/', general_views.search, name='search'),

    # Shop URLS's
    path('tienda/', include((shop_urls, 'shop'), namespace='shop')),

    # Sport URLS's
    path('deporte/', include((sportapp_urls, 'sportapp'), namespace='sportapp')),

    # Health URLS's
    path('salud/', include((healthapp_urls, 'healthapp'), namespace='healthapp')),

    # Nutrition URLS's
    path('nutricion/', include((nutritionapp_urls, 'nutritionapp'), namespace='nutritionapp')),

    # Statistics URLS's
    path('estadisticas/', general_views.statistics, name='statistics'),

    # Awards URLS's
    path('premios/', include((awards_urls, 'awards'), namespace='awardsapp')),

    # Editor de Texto HTML URL's
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Registro URLS's
    # url(r'^mi_cuenta/$', include('django.contrib.auth.urls')),
    path('registro/', general_views.custom_registration, name='custom_register'),
    #url(r'^registro/completado/$', general_views.registration_complete, name='custom_register_complete'),
    #url(r'^registro/cancelado/$', general_views.registration_disallowed, name='registration_disallowed'),

    # Profile URLS's
    path('mi_cuenta/<str:username>/', general_views.profile, name='profile'),
    # url(r'^mi_cuenta/(?P<username>\w+)/pedidos/$', general_views.ships, name='ships'),
    path('mi_cuenta/<str:username>/deporte/', general_views.sport_profile, name='sport_profile'),
    path('mi_cuenta/<str:username>/nutricion/', general_views.nutrition_profile, name='nutrition_profile'),
    path('mi_cuenta/<str:username>/salud/', general_views.health_profile, name='health_profile'),
    #url(r'^mi_cuenta/(?P<username>\w+)/premios/$', general_views.awards_profile, name='awards_profile'),
    path('mi_cuenta/<str:username>/colaborador/', general_views.collaborator_profile, name='collaborator_profile'),

    # Calendar URLS's
    path('calendario/', include((events_urls, 'events'), namespace='calendar')),

    # Company URLS's
    #url(r'^empresas/(?P<company>\w+)/empresa/$', views.company, name='company'),

    # Collaborators URLS's
    #url(r'^colaboradores/(?P<username>\w+)/$', views.company, name='collaborators'),

    # Login URLS's
    path('acceso/', general_views.custom_login, name='custom_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('activacion/<uuid:uidb64>/<uuid:token>/', general_views.custom_activation, name='activation'),
    path('reset/', general_views.custom_reset_password, name='reset'),
    path('reset_form/<uuid:uidb64>/<uuid:token>/', general_views.custom_reset_password_form, name='reset_form'),


    #url(r'^mi_cuenta/password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    #url(r'^mi_cuenta/password_change_done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #url(r'^mi_cuenta/password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #url(r'^mi_cuenta/password_reset_done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #url(r'^mi_cuenta/password_confirm/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #url(r'^mi_cuenta/password_reset_complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

# Format suffixes
#urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthylife/events/views.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.shortcuts import render, redirect, get_object_or_404, reverse
from healthylifeapp import views as general_views
from events import models as events_models
from events import forms as events_forms
import datetime
from calendar import monthrange
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from shop import views as shop_views

# Calendar views
def next_events(request):
    pass


def list_events(request):
    pass


@login_required(redirect_field_name='custom_login')
def month(request, username, year, month):
    """
    Calendar month view
    Calulate days of month
    """
    month = int(month)
    year = int(year)

    if month == 0:
        year = year-1
        month = 12

        month = unicode(month)
        year = unicode(year)

        return redirect('calendar:month_calendar', username=username, year=year, month=month)

    if month == 13:
        year = year+1
        month = 1

        month = unicode(month)
        year = unicode(year)

        return redirect('calendar:month_calendar', username=username, year=year, month=month)

    first_day_of_week_number = monthrange(year, month)[0]
    last_day_number = monthrange(year, month)[1]

    previous_month = month-1
    next_month = month+1

    days = []
    max_number = None
    num = 1

    # calculate minimum and maximum calendar days
    if last_day_number == 28:
        if first_day_of_week_number == 0:
            max_number = 28
        else:
            max_number = 35
    elif last_day_number == 29:
        max_number = 35
    elif last_day_number == 30:
        if first_day_of_week_number <= 5:
            max_number = 35
        else:
            max_number = 42
    elif last_day_number == 31:
        if first_day_of_week_number <= 4:
            max_number = 35
        else:
            max_number = 42
    else:
        max_number = None

    #create calendar days
    for item in range(0, max_number):
        if item >= first_day_of_week_number and num <= last_day_number:
            days.append(num)
            num += 1
        else:
            days.append(0)

    month_name = getMonthName(month)
    month = unicode(month)
    year = unicode(year)
    previous_month = unicode(previous_month)
    next_month = unicode(next_month)

    shoppingcart = shop_views.getShoppingCart(request.session)

    return render(request, 'month_calendar.html', {
        'days': days,
        'month': month,
        'month_name': month_name,
        'year': year,
        'previous_month': previous_month,
        'next_month': next_month,
        'event_form': getEventform(request),
        'shoppingcart': shoppingcart,
        # 'type': 1,
        #'current_day': current_day,
        #'current_month': current_month,
        #'current_year': current_year
    })


@login_required(redirect_field_name='custom_login')
def day(request, username, year, month, day):
    month = int(month)
    year = int(year)
    day = int(day)

    last_day_number = monthrange(year, month)[1]

    if day > last_day_number:
        month = month+1
        day = 1

        if month == 13:
            year = year+1
            month = 1

        month = unicode(month)
        year = unicode(year)
        day = unicode(day)

        return redirect('calendar:day_calendar', username=username, year=year, month=month, day=day)

    if day == 0:
        month = month-1

        if month == 0:
            year = year-1
            month = 12

        day = monthrange(year, month)[1]

        month = unicode(month)
        year = unicode(year)
        day = unicode(day)

        return redirect('calendar:day_calendar', username, year, month, day)

    day_name = getDayName(datetime.datetime(year, month, day).weekday())

    month_name = getMonthName(month)
    previous_day = day-1
    next_day = day+1
    previous_day = unicode(previous_day)
    next_day = unicode(next_day)

    shoppingcart = shop_views.getShoppingCart(request.session)

    return render(request, 'day_calendar.html', {
        'day': day,
        'month': month,
        'month_name': month_name,
        'day_name': day_name,
        'year': year,
        'previous_day': previous_day,
        'next_day': next_day,
        'event_form': getEventform(request),
        "search_form": general_views.getSearchForm(),
        'shoppingcart': shoppingcart,
    })


class EventUpdateView(LoginRequiredMixin, UpdateView):
    """
    https://stackoverflow.com/questions/7122071/how-can-i-fill-up-form-with-model-object-data
    https://ccbv.co.uk/projects/Django/1.5/django.views.generic.edit/UpdateView/
    """
    model = events_models.Event
    template_name = 'event.html'
    fields = ['title', 'description']
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    context_object_name = 'event'
    template_name_name = 'event_update_form'


def add_event(request):
    print("funcion añadir un evento")
    if request.method == 'POST':
        print("metodo post")
        event_form = events_forms.EventForm(request.POST)
        if event_form.is_valid():
            print("formulario válido")
            data = event_form.cleaned_data
            event = event_form.save(commit=False)
            event.owner = request.user
            event.save()
            print(data)
        else:
            print("formulario no válido")
    else:
        print("metodo get")
        event_form = events_forms.EventForm()

    return redirect('home')


# Common Functions
def getEventform(request):
    print("funcion para obtener el formulario de evento")
    if request.method == 'POST':
        print("metodo post")
        return events_forms.EventForm(request.POST)
    else:
        print("metodo get")
        return events_forms.EventForm()


def getMonthName(month):
    if (month == 1):
        return 'Enero'
    if (month == 2):
        return 'Febrero'
    if (month == 3):
        return 'Marzo'
    if (month == 4):
        return 'Abril'
    if (month == 5):
        return 'Mayo'
    if (month == 6):
        return 'Junio'
    if (month == 7):
        return 'Julio'
    if (month == 8):
        return 'Agosto'
    if (month == 9):
        return 'Septiembre'
    if (month == 10):
        return 'Octubre'
    if (month == 11):
        return 'Noviembre'
    if (month == 12):
        return 'Diciembre'

def getDayName(number):
    if (number == 0):
        return 'Lunes'
    if (number == 1):
        return 'Martes'
    if (number == 2):
        return 'Miércoles'
    if (number == 3):
        return 'Jueves'
    if (number == 4):
        return 'Viernes'
    if (number == 5):
        return 'Sábado'
    if (number == 6):
        return 'Domingo'





#

healthylife/templates/calendar/add_event.html
{% load static %}
{% load calendar_tags %}

<!-- Add Event Button -->
<div class="row">
  <div class="col-md-12">
    <div class="filter__menu__container">
      <div class="product__menu">
        <button data-filter="*"  class="is-checked">Todo</button>
        <button data-filter=".cat--1">Deporte</button>
        <button data-filter=".cat--2">Nutrición</button>
        <button data-filter=".cat--3">Salud</button>
      </div>
      <div class="filter__box">
        <a class="calendar__filter__menu" href="#"><span class="ti-search"></span> Añadir Evento</a>
      </div>
    </div>
  </div>
</div>

<!-- Start Add Event Form Area -->
<div class="calendar__filter__wrap">
  <div class="filter__cart">
    <div class="filter__cart__inner">

      <!-- Filter Title-->
      <div class="calendar__filter__menu__close__btn">
        <a href="#"><i class="zmdi zmdi-close"></i></a>
      </div>

      <div class="filter__content">

        <form action="{% url 'calendar:add_event' %}" method="POST">
          {% csrf_token %}

          {{ event_form.as_p }}
          
          <!-- Filter Button -->
          <div class="fiter__content__inner">
            <div class="single__filter">
              <div class="contact-btn">
                <input type="submit" class="fv-btn" value="Añadir">
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

healthylife/templates/calendar/calendar.html
{% extends "base.html" %}
{% load static %}

{% block calendar %}

<!-- Calendar Breadcrumbs Area -->
<div class="ht__bradcaump__area" style="background: rgba(0, 0, 0, 0) url({% static 'images/calendar_banner_1.jpg' %}) no-repeat scroll center center / cover ;">
  <div class="ht__bradcaump__wrap">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="bradcaump__inner text-center">
            <h2 class="bradcaump-title">Shop Page</h2>
            <nav class="bradcaump-inner">
              <a class="breadcrumb-item" href="index.html">Home</a>
              <span class="brd-separetor">/</span>
              <span class="breadcrumb-item active">Shop Page</span>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Start Calendar Area -->
<section class="htc__contact__area ptb--120 bg__white">
  <div class="container">
    <!--<div class="htc__product__container">-->

      {% include 'add_event.html' %}

      {% block month %}
      {% endblock %}

      <div class="row">
      {% block day %}
      {% endblock %}

      {% block event %}
      {% endblock %}
      </div>

    <!--</div>-->
  </div>
</section>

{% endblock %}

healthylife/templates/calendar/day_calendar.html
{% extends "calendar.html" %}
{% load static %}
{% load calendar_tags %}

{% block day %}

<!-- Start Day Calendar Area -->
      <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
        <div class="htc__contact__container">

      <div class="monthly-header">
        <!--<div class="monthly-header-title">
          <div class="monthly-header-title-date">-->
            {{ day_name }} {{ day }} de
            <a href="{% url 'calendar:month_calendar' username=request.user.username year=year month=month %}">{{ month_name }}</a>
            del {{ year }}
          <!--</div>
        </div>-->
        <a href="{% url 'calendar:day_calendar' username=request.user.username year=year month=month day=previous_day %}" class="monthly-prev"></a>
        <a href="{% url 'calendar:day_calendar' username=request.user.username year=year month=month day=next_day %}" class="monthly-next"></a>
      </div>
      <div class="monthly-day-wrap">
        <div class="monthly-week">
      {% getEvents request.user.id year month day type=None as events %}
      {% for event in events %}
        <li>
          <p>
            <a href="{% url 'calendar:detail_event' event.slug %}">{{ event.title }}</a>
          </p>
        </li>
      {% endfor %}
    </div>
    </div>

    </div>
    </div>


{% endblock %}

healthylife/templates/calendar/event.html
{% extends "calendar.html" %}
{% load static %}
{% load calendar_tags %}

{% block event %}

<!-- Event Information Area -->
      <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 smt-30 xmt-30">
        <div class="map-contacts">
          <!--<form id="contact-form" method="POST">-->
          <form method="POST">
            {% csrf_token %}

            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  <h3>Privacidad</h3>
                  {{ event.privacity }}
                </div>
            </div>
            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  <h3>Categoría</h3>
                  {{ event.type }}
                </div>
            </div>
            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  {{ event.title }}
                </div>
            </div>
            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  {{ event.description }}
                </div>
            </div>
            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  {{ event.address }}
                </div>
            </div>
            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  <h3>Inicio</h3>
                  {{ event.start }}
                </div>
            </div>
            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  <h3>Fin</h3>
                  {{ event.end }}
                </div>
            </div>
            <!-- Event Form Area -->
            <div class="single-contact-form">
                <div class="contact-box subject">
                  <h3>Privacidad</h3>
                  {{ event.notes }}
                </div>
            </div>

            <div class="contact-btn">
                <input type="submit" class="fv-btn" value="Modificar">
            </div>
          </form>
        </div>
      </div>

{% endblock %}

healthylife/templates/calendar/month_calendar.html
{% extends "calendar.html" %}
{% load static %}
{% load calendar_tags %}

{% block month %}

<!-- Start Month Calendar Area -->

      <div class="row">
      <div class="monthly-header">
        <!--<div class="monthly-header-title">-->
          {{ month_name }} del {{ year }}
        <!--</div>-->
        <a href="{% url 'calendar:month_calendar' username=request.user.username year=year month=previous_month %}" class="monthly-prev"></a>
        <a href="{% url 'calendar:month_calendar' username=request.user.username year=year month=next_month %}" class="monthly-next"></a>
      </div>
      <div class="monthly-day-title-wrap">
        <div>lun.</div>
        <div>mar.</div>
        <div>mié.</div>
        <div>jue.</div>
        <div>vie.</div>
        <div>sáb.</div>
        <div>dom.</div>
      </div>

      <div class="monthly-day-wrap">
        <div class="monthly-week">
        {% for day in days %}
          {% if day > 0 %}
            <div class="m-d monthly-day monthly-day-event">
              <div class="monthly-day-number">
                <a href="{% url 'calendar:day_calendar' username=request.user.username year=year month=month day=day %}">{{ day }}</a>
              </div>
              <div class="monthly-indicator-wrap">
                <!-- lista de eventos -->
                {% isToday year=year month=month day=day as today %}
                {% if today %}
                  <p>Hoy</p>
                {% endif %}
                <ul>
                {% getEvents request.user.id year month day type=None as events %}
                {% for event in events %}
                  <li>
                    <p>
                      <a href="{% url 'calendar:detail_event' event.slug %}">{{ event.title }}</a>
                    </p>
                  </li>
                {% endfor %}
              </ul>
              </div>
            </div>
          {% else %}
            <div class="m-d monthly-day-blank"></div>
          {% endif %}
          {% isMultipleBiggerThanZero number=forloop.counter as multipleBiggerThanZero %}
          {% if multipleBiggerThanZero %}
            </div>
            <div class="monthly-week">
          {% endif %}
        {% endfor %}
        </div>
      </div>
    </div>

{% endblock %}

healthylife/templates/calendar/next_events.html
{% load static %}

{% now "m" as current_month %}
{% now "Y" as current_year %}
{% now "d" as current_day %}

{% block next_events %}

<!-- Start Next Events Home Area -->
<section class="htc__blog__area bg__white pb--100">
  <div class="container">

    <!-- Start Title Area -->
    <div class="row">
      <div class="col-xs-12">
        <div class="section__title text-center">
          <h2 class="title__line">Próximos Eventos</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="blog__wrap clearfix mt--60 xmt-30">

        <!-- Start Single Event -->
        {% for post in last_posts %}
          <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
            <div class="blog foo">
              <div class="blog__inner">
                <div class="blog__thumb">
                  {% for item in post.album.image_set.all %}
                    {% if item.header_image %}
                      <a href="">
                        <img src="{{ item.image.url }}" alt="blog images">
                      </a>
                    {% endif %}
                  {% endfor %}
                  <div class="blog__post__time">
                    <div class="post__time--inner">
                      <span class="date">{{ post.created_date }}</span>
                    </div>
                  </div>
                </div>
                <div class="blog__hover__info">
                  <div class="blog__hover__action">
                    <ul class="bl__meta">
                      <li>By :
                        <a href="{% url 'blog:author_posts' username=post.author.username %}">{{ post.author.username }}</a>
                      </li>
                      <li>
                        <a href="{% url 'blog:category_posts' category=post.category.slug %}">{{ post.category.name }}</a>
                      </li>
                    </ul>
                    <p class="blog__des"><a href="{% url 'blog:detail_post' post_slug=post.slug %}">{{ post.title }}</a></p>
                    <div class="blog__btn">
                      <a class="read__more__btn" href="{% url 'blog:detail_post' post_slug=post.slug %}">Leer Más</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <!-- Go To Events Button -->
        <div class="row mt--60">
            <div class="col-md-12">
                <div class="htc__loadmore__btn">
                  <a href="{% url 'calendar:list_events' %}">Ver más Eventos</a>
                </div>
            </div>
        </div>
  </div>
</section>

{% endblock %}