healthylife/api/urls.py
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include

from api import views as api_views

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [

    path('', api_views.api, name='api_home'),

    # API Blog URLS
    # path(r'^blog/posts/$', api_views.APIPostList.as_view(), name='post-list'),
    path('blog/posts/', api_views.api_list_posts, name='post-list'),
    # path(r'^api/posts/(?P<pk>\d+)/$', blog_views.APIPostDetail.as_view(), name='post-detail'),

    path('blog/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    # path(r'^api/categories/(?P<pk>\d+)/$', blog_views.APICategoryDetail.as_view(), name='category-detail'),

    path('blog/comments/', api_views.APICommentList.as_view(), name='comment-list'),
    # path(r'^api/comments/(?P<pk>\d+)/$', blog_views.APICommentDetail.as_view(), name='comment-detail'),

    path('blog/tags/', api_views.APITagList.as_view(), name='tag-list'),
    # path(r'^api/tags/(?P<pk>\d+)/$', blog_views.APITagDetail.as_view(), name='tag-detail'),

    # path(r'^users/$', blog_views.APIUserList.as_view(), name='user-list'),
    # path(r'^users/(?P<pk>\d+)/$', blog_views.APIUserDetail.as_view(), name='user-detail'),

    # path(r'^users/login$', blog_views.userLoginAPI, name='user-login-api'),
    # path(r'^users/register/$', blog_views.userRegistrationAPI, name='user-register-api'),


    # API Shop URLS
    path('shop/products/', api_views.api_list_products, name='product-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='product-list'),

    path('shop/categories/', api_views.APICategoryList.as_view(), name='category-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='category-detail'),

    path('shop/reviews/', api_views.APIReviewList.as_view(), name='review-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='review-detail'),

    path('shop/tags/', api_views.APIReviewList.as_view(), name='tag-list'),
    #path(r'^api/products/$', blog_views.APIProductList.as_view(), name='tag-detail'),

    # API Blog URLS
    path('awards/', api_views.api_list_awards, name='awards-list'),

    # API General URLS
    path('users/', api_views.APIUserList.as_view(), name='user-list'),
    path('users/register/', api_views.custom_registration_api, name='user-register'),
    path('api-token-auth/', obtain_jwt_token),

]











#

healthylife/awards/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include
from awards import views as awards_views

urlpatterns = [

    # Awards URLS's
    path('', awards_views.awards, name='awards'),
    path('', awards_views.awards, name='search_awards'),

    path('<str:username>/conseguidos/', awards_views.awards_profile, name='awards_profile'),

    path('<str:award_slug>/', awards_views.award_detail, name='award_detail'),

    # Coupon Urls
    path('cupon/', awards_views.coupon, name='coupon'),
]

healthylife/blog/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from healthylife import settings
from blog import views as blog_views

urlpatterns = [

    # Blog URLS's
    path('posts/', blog_views.list_posts, name='list_post'),
    path('posts/', blog_views.list_posts, name='blog_search'),

    # hacer generica
    #path(r'^blog/subscripcion/$', blog_views.subscribe, name='subscribe'),

    path('posts/<str:post_slug>/', blog_views.detail_post, name='detail_post'),
    path('posts/<str:post_slug>/comentario', blog_views.add_comment, name='add_comment'),

    path('comentarios/<int:comment_id>/borrar/', blog_views.delete_comment, name='delete_comment'),

    # path(r'^blog/(?P<post_slug>\w+)/(?P<comment_parent_id>\w+)/comentado/$', views.comment, name='comment'),
    path('categorias/<str:category>/', blog_views.category_posts, name='category_posts'),
    path('autores/<str:username>/', blog_views.author_posts, name='author_posts'),
    path('etiquetas/<str:tag_slug>/', blog_views.tag_posts, name='tag_posts'),

]

healthylife/events/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from django.urls import path, include, re_path
from events import views as calendar_views
from events import models as calendar_models

urlpatterns = [

    # Calendar URLS's
    path('<str:username>/<int:year>/<int:month>/', calendar_views.month, name='month_calendar'),
    path('<str:username>/<int:year>/<int:month>/<int:day>/', calendar_views.day, name='day_calendar'),

    # Event Urls
    path('eventos/', calendar_views.list_events, name='list_events'),
    path('eventos/nuevo/', calendar_views.add_event, name='add_event'),
    path('eventos/<str:slug>/', calendar_views.EventUpdateView.as_view(), name='detail_event'),
]

healthylife/healthylife/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import DetailView, ListView, UpdateView
from rest_framework.urlpatterns import format_suffix_patterns

from healthylifeapp import views as general_views
from healthylife import settings
from shop import views as shop_views
from shop import urls as shop_urls
from events import views as calendar_views
from events import urls as events_urls
from api import urls as api_urls
from blog import urls as blog_urls
from sportapp import urls as sportapp_urls
from nutritionapp import urls as nutritionapp_urls
from healthapp import urls as healthapp_urls
from awards import urls as awards_urls

admin.site.site_header = 'Barbastro Se Mueve'
admin.autodiscover()

urlpatterns = [

    # Pages URLS's
    path('', general_views.home, name='home'),
    path('conocenos/', general_views.know_us, name='know_us'),
    path('conocenos/colaboradores/<str:username>/', general_views.know_us_collaborator, name='collaborator'),
    path('conocenos/empresas/<str:companyname>/', general_views.know_us_company, name='company'),

    path('trabaja_con_nosotros/', general_views.work_with_our, name='work_with_our'),
    path('informacion_legal/', general_views.legal_information, name='legal_information'),
    path('contacto/', general_views.contact, name='contact'),

    # Subscribe URLS
    path('subscripcion/', general_views.subscribe, name='subscribe'),

    # Admin URLS's
    path('administracion/', admin.site.urls),

    # API Urls
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include((api_urls, 'api'), namespace='api')),

    # Blog URLS's
    path('blog/', include((blog_urls, 'blog'), namespace='blog')),

    # Search URLS's
    path('resultado_busqueda/', general_views.search, name='search'),

    # Shop URLS's
    path('tienda/', include((shop_urls, 'shop'), namespace='shop')),

    # Sport URLS's
    path('deporte/', include((sportapp_urls, 'sportapp'), namespace='sportapp')),

    # Health URLS's
    path('salud/', include((healthapp_urls, 'healthapp'), namespace='healthapp')),

    # Nutrition URLS's
    path('nutricion/', include((nutritionapp_urls, 'nutritionapp'), namespace='nutritionapp')),

    # Statistics URLS's
    path('estadisticas/', general_views.statistics, name='statistics'),

    # Awards URLS's
    path('premios/', include((awards_urls, 'awards'), namespace='awardsapp')),

    # Editor de Texto HTML URL's
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Registro URLS's
    # url(r'^mi_cuenta/$', include('django.contrib.auth.urls')),
    path('registro/', general_views.custom_registration, name='custom_register'),
    #url(r'^registro/completado/$', general_views.registration_complete, name='custom_register_complete'),
    #url(r'^registro/cancelado/$', general_views.registration_disallowed, name='registration_disallowed'),

    # Profile URLS's
    path('mi_cuenta/<str:username>/', general_views.profile, name='profile'),
    # url(r'^mi_cuenta/(?P<username>\w+)/pedidos/$', general_views.ships, name='ships'),
    path('mi_cuenta/<str:username>/deporte/', general_views.sport_profile, name='sport_profile'),
    path('mi_cuenta/<str:username>/nutricion/', general_views.nutrition_profile, name='nutrition_profile'),
    path('mi_cuenta/<str:username>/salud/', general_views.health_profile, name='health_profile'),
    #url(r'^mi_cuenta/(?P<username>\w+)/premios/$', general_views.awards_profile, name='awards_profile'),
    path('mi_cuenta/<str:username>/colaborador/', general_views.collaborator_profile, name='collaborator_profile'),

    # Calendar URLS's
    path('calendario/', include((events_urls, 'events'), namespace='calendar')),

    # Company URLS's
    #url(r'^empresas/(?P<company>\w+)/empresa/$', views.company, name='company'),

    # Collaborators URLS's
    #url(r'^colaboradores/(?P<username>\w+)/$', views.company, name='collaborators'),

    # Login URLS's
    path('acceso/', general_views.custom_login, name='custom_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('activacion/<uuid:uidb64>/<uuid:token>/', general_views.custom_activation, name='activation'),
    path('reset/', general_views.custom_reset_password, name='reset'),
    path('reset_form/<uuid:uidb64>/<uuid:token>/', general_views.custom_reset_password_form, name='reset_form'),


    #url(r'^mi_cuenta/password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    #url(r'^mi_cuenta/password_change_done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #url(r'^mi_cuenta/password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #url(r'^mi_cuenta/password_reset_done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #url(r'^mi_cuenta/password_confirm/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #url(r'^mi_cuenta/password_reset_complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

# Format suffixes
#urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthylife/shop/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.conf.urls import url
from django.urls import path, include, re_path
from django.conf.urls.static import static
from shop import views as shop_views
from django.conf import settings

urlpatterns = [

    # Products Shop Urls
    path('productos/', shop_views.product_list, name='product_list'),
    path('productos/<str:product_slug>/', shop_views.product_detail, name='product_detail'),
    path('productos/<str:product_slug>)/comentario', shop_views.add_review, name='add_review'),

    # Category Urls
    path('categorias/<str:shop_category_slug>/', shop_views.product_list, name='product_list_category'),

    #Search Urls
    path('productos/', shop_views.product_list, name='shop_search'),

    # Payments Urls
    path('pago/realizado', shop_views.payment_done, name='payment_done'),
    path('pago/cancelado', shop_views.payment_canceled, name='payment_canceled'),

    # Shipping Urls
    path('direccion_envio/', shop_views.address_checkout, name='address_checkout'),
    path('metodo_envio/', shop_views.shipping_checkout, name='shipping_checkout'),
    path('metodo_pago/', shop_views.payment_checkout, name='payment_checkout'),

    path('pedido/', shop_views.order_checkout, name='order_checkout'),

    # ShopingChart Urls
    path('carrito/', shop_views.shoppingcart, name='shoppingcart_detail'),
    path('carrito/nuevo/<int:product_id>/', shop_views.cartAdd, name='shoppingcart_add'),

    #Profile Urls
    path('mi_cuenta/<str:username>/pedidos/', shop_views.ships, name='ships'),

]

healthylife/api/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

healthylife/templates/api.html
{% extends 'base.html' %}

{% block api %}

  <p>
  Blog API<br>
  <a href="{% url 'api:post-list' %}">Posts</a><br>
  <a href="{% url 'api:category-list' %}">Blog Categories</a><br>
  <a href="{% url 'api:comment-list' %}">Comments</a><br>
  <a href="{% url 'api:tag-list' %}">Blog Tags</a><br>
  Shop API<br>
  <a href="{% url 'api:product-list' %}">Products</a><br>
  <a href="{% url 'api:category-list' %}">Shop Categories</a><br>
  <a href="{% url 'api:review-list' %}">Reviews</a><br>
  <a href="{% url 'api:tag-list' %}">Tags</a><br>
  </p>

{% endblock %}

healthylife/templates/base.html
{% load static %}

{% now "n" as current_month %}
{% now "Y" as current_year %}
{% now "d" as current_day %}

<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Barbastro Se Mueve </title>

    <!--<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>-->
    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- All css files are included here. -->
    <!-- Bootstrap fremwork main css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Owl Carousel main css -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <!-- This core.css file contents all plugings css file. -->
    <link rel="stylesheet" href="{% static 'css/core.css' %}">

    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="{% static 'css/shortcode/shortcodes.css' %}">

    <!-- Theme main style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Responsive css -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <!-- User style -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Calendar style -->
    <link rel="stylesheet" href="{% static 'css/monthly.css' %}">

  </head>
  <body>

    <div class="wrapper fixed__footer home-v5">

      {% include 'header.html' %}

      <div class="body__overlay"></div>
      <div class="offset__wrapper">

        {% include 'search.html' %}

        {% include 'navbar_menu.html'%}

        {% include 'shoppingcart_menu.html'%}

        {% include 'profile_menu.html'%}

      </div>

        {% block home %}
        {% endblock %}

        {% block know_us %}
        {% endblock %}

        {% block company %}
        {% endblock %}

        {% block collaborator %}
        {% endblock %}

        {% block sport_section %}
        {% endblock %}

        {% block nutrition_section %}
        {% endblock %}

        {% block health_section %}
        {% endblock %}

        {% block blog %}
        {% endblock %}

        {% block shop %}
        {% endblock %}

        {% block shoppincart %}
        {% endblock %}

        {% block ships %}
        {% endblock %}

        {% block address_checkout %}
        {% endblock %}

        {% block shipping_checkout %}
        {% endblock %}

        {% block payment_checkout %}
        {% endblock %}

        {% block order_checkout %}
        {% endblock %}

        {% block product_detail %}
        {% endblock %}

        {% block profile %}
        {% endblock %}

        {% block collaborator_profile %}
        {% endblock %}

        {% block sport_profile %}
        {% endblock %}

        {% block nutrition_profile %}
        {% endblock %}

        {% block health_profile %}
        {% endblock %}

        {% block statistics %}
        {% endblock %}

        {% block awards %}
        {% endblock %}

        {% block legal_information %}
        {% endblock %}

        {% block work_with_our %}
        {% endblock %}

        {% block contact %}
        {% endblock %}

        {% block registration %}
        {% endblock %}

        {% block login %}
        {% endblock %}

        {% block password_reset %}
        {% endblock %}

        {% block password_reset_form %}
        {% endblock %}

        {% block password_reset_done %}
        {% endblock %}

        {% block admin %}
        {% endblock %}

        {% block api %}
        {% endblock %}

        {% block calendar %}
        {% endblock %}

        {% include 'footer.html' %}

  </div>



  </body>

  <!-- Modernizr JS -->
  <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>

  <!-- jquery latest version -->
  <script src="{% static 'js/vendor/jquery-1.12.0.min.js' %}"></script>

  <!-- Bootstrap framework js -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- All js plugins included in this file. -->
  <script src="{% static 'js/plugins.js' %}"></script>
  <script src="{% static 'js/slick.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>

  <!-- Waypoints.min.js. -->
  <script src="{% static 'js/waypoints.min.js' %}"></script>

  <!-- Main js file that contents all jQuery plugins activation. -->
  <script src="{% static 'js/main.js' %}"></script>

  <!-- Custom Javascript -->
  <script src="{% static 'js/custom_js.js' %}"></script>

  <!-- Social Share Icons -->
  <script src="//platform-api.sharethis.com/js/sharethis.js#property=5b4c598c77b6460012241341&product=inline-share-buttons"></script>

</html>

healthylife/templates/call_to_action.html
{% load static %}

<!-- Start Call To Action Area -->
<section class="htc__new__product bg__white ptb--100">
            <div class="container">
                <div class="row">
                    <div class="new__product__wrap clearfix">

                        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                            <div class="new__product foo">
                                <div class="new__product__thumb">
                                    <a href="{% url 'custom_register' %}">
                                        <img src="{% static 'images/call_to_action_user.jpg' %}" alt="new product">
                                    </a>
                                </div>
                                <div class="new__product__details">
                                    <h2>Mejora tu salud</h2>
                                    <div class="new__product__btn">
                                        <a class="htc__btn shop__now__btn" href="{% url 'custom_register' %}">Registrate como usuario</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 smt-30 xmt-30">
                            <div class="new__product text__align--left foo">
                                <div class="new__product__thumb">
                                    <a href="{% url 'work_with_our' %}">
                                        <img src="{% static 'images/call_to_action_collaborator.jpg' %}" alt="new product">
                                    </a>
                                </div>
                                <div class="new__product__details">
                                    <h2>Mejora la salud de los demás</h2>
                                    <div class="new__product__btn">
                                        <a class="htc__btn shop__now__btn" href="{% url 'work_with_our' %}">Registrate como colaborador</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End New Product -->
                    </div>
                </div>
            </div>
        </section>

healthylife/templates/company.html
{% extends 'base.html' %}

{% block company %}
<p>Información de la Empresa</p>
    <hr>
    {{ company.company_name }}<br>
    {{ company.description }}<br>
    {{ company.phone }}<br>
    {{ company.web }}<br>
    <img src="{{ company.company_image.url }}">
{% endblock %}

healthylife/templates/form.html
{% load static %}

{% block generic_form %}
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

healthylife/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}

{% block home %}

  {% include 'slide.html' %}

  {% include 'call_to_action.html' %}

  {% include 'last_posts.html' %}

  <!--WIDGET WEATHER-->

{% endblock %}

healthylife/templates/navbar_menu.html
{% load static %}

<!-- Start Navbar Icon Menu Area -->
<div class="offsetmenu home-five bg__gray">
  <div class="offsetmenu__inner sidebar__menu--inner">

    <div class="offsetmenu__close__btn">
      <a href="#"><i class="zmdi zmdi-close"></i></a>
    </div>

    <!-- Start Logo Area -->
    <div class="off__contact">
      <div class="logo">
        <a href="{% url 'home' %}">
          <img src="{% static 'images/logo_titulo.png' %}" alt="logo">
        </a>
      </div>
    </div>

    <!-- Start Navbar Area -->
    <nav>
      <ul class="sidebar__menu">
        <!--<li><a href="{% url 'home' %}">Inicio</a></li>-->
        <li><a href="{% url 'know_us' %}">Conocenos</a></li>
        <li><a href="{% url 'sportapp:sport' %}">Deporte</a></li>
        <li><a href="{% url 'nutritionapp:nutrition' %}">Nutricion</a></li>
        <!--<li><a href="{% url 'healthapp:health' %}">Salud</a></li>-->
        <li><a href="{% url 'awardsapp:awards' %}">Premios</a></li>
        <!--<li><a href="{% url 'know_us' %}">Proyecto</a></li>-->
        <li><a href="{% url 'blog:list_post' %}">Blog</a></li>
        <!--<li><a href="{% url 'shop:product_list' %}">Tienda</a></li>-->
        <li><a href="{% url 'contact' %}">Contacto</a></li>
      </ul>
    </nav>

    <!-- Start Option Area -->
    <!--<div class="offset__widget">
      <div class="offset__single">
        <h4 class="offset__title">Language</h4>
        <ul>
          <li><a href="#"> Engish </a></li>
          <li><a href="#"> French </a></li>
          <li><a href="#"> German </a></li>
        </ul>
      </div>
      <div class="offset__single">
        <h4 class="offset__title">Currencies</h4>
        <ul>
          <li><a href="#"> USD : Dollar </a></li>
          <li><a href="#"> EUR : Euro </a></li>
          <li><a href="#"> POU : Pound </a></li>
        </ul>
      </div>
    </div>-->

    <!-- Start Social Menu Area -->
    <!--<div class="offset__sosial__share">
      <h4 class="offset__title">SIGUENOS</h4>
      <ul class="off__soaial__link">
        <li><a href="https://twitter.com/BarbastroSMueve" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
        <li><a href="https://www.instagram.com/barbastrosemueve/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
        <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
        <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
        <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-google-plus"></i></a></li>
        <li><a href="https://www.facebook.com/BarbastroSeMueve/" target="_blank"><i class="zmdi zmdi-youtube"></i></a></li>
      </ul>
    </div>-->

  </div>
</div>

healthylife/templates/profile_menu.html
<!-- Start Profiel Icon Menu Area -->
<div class="profile">
  <div class="profile__inner">

    <div class="offsetmenu__close__btn">
      <a href="#"><i class="zmdi zmdi-close"></i></a>
    </div>

      <ul class="profile__btn">
        {% if not user.is_authenticated %}
          <li>
            <a href="{% url 'custom_login' %}">Acceder</a>
          </li>
        {% else %}
          <li>
            <a href="{% url 'profile' username=user.username %}">{{ user.username }}</a>
          </li>
          {% if user.is_staff %}
            <li>
              <a href="{% url 'collaborator_profile' username=user.username %}">Colaborador</a>
            </li>
            <li>
              <a href="/administracion" target="_blank">Administracion</a>
            </li>
          {% endif %}
          <!--<li>
            <a href="{% url 'sport_profile' username=user.username %}">Deporte</a>
          </li>
          <li>
            <a href="{% url 'nutrition_profile' username=user.username %}">Nutricion</a>
          </li>
          <li>
            <a href="{% url 'health_profile' username=user.username %}">Salud</a>
          </li>
          <li>
            <a href="{% url 'awardsapp:awards_profile' username=user.username %}">Premios</a>
          </li>
          <li>
            <a href="{% url 'shop:ships' username=user.username %}">Pedidos</a>
          </li>-->
          <!--<li>
            <a href="{% url 'calendar:month_calendar' username=user.username year=current_year month=current_month %}">Calendario</a>
          </li>-->
          <li class="profile__checkout"><a href="{% url 'logout' %}">Desconectar</a></li>
        {% endif %}
      </ul>

  </div>
</div>

healthylife/templates/subscribe.html
{% load static %}

    <form method="POST" action="{% url 'subscribe' %}" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
      {% csrf_token %}
      <div id="mc_embed_signup_scroll" class="htc__news__inner">
        <div class="news__input">
          {{ subscribe_form.as_p }}
        </div>
        <div class="clearfix subscribe__btn">
          <input type="submit" value="Send" name="subscribe" id="mc-embedded-subscribe" class="bst__btn btn--white__color">
        </div>
      </div>
    </form>